services:
  backend-mock:
    build:
      dockerfile: ./docker/backend-mock.dockerfile
      context: .
    image: rcjeferson/backend-mock
    container_name: backend-mock
    volumes:
      - .:/var/www
    restart: always
    entrypoint: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    environment:
      - STAGE=workshop
